export const LOAD_REPOSITORIES_LOADING =
  'REPOSITORIES/LOAD_REPOSITORIES_LOADING';
export const LOAD_REPOSITORIES_SUCCESS =
  'REPOSITORIES/LOAD_REPOSITORIES_SUCCESS';
export const LOAD_REPOSITORIES_FAILURE =
  'REPOSITORIES/LOAD_REPOSITORIES_FAILURE';
export const SET_PAGE = 'REPOSITORIES/SET_PAGE';
export const SET_QUERY = 'REPOSITORIES/SET_QUERY';
